name: "Deploy to Cloud Run"
description: "Deploy a container image to Google Cloud Run"
author: "Shakr Media Co., Ltd."
inputs:
  github_token:
    description: "GitHub token to make API request (use github.token)"
    required: true
  github_environment:
    description: "Name of the GitHub environment"
    required: true
  service_name:
    description: "Name of the already existing Cloud Run service"
    required: true
  project_id:
    description: "Google Cloud Platform project id"
    required: true
  region:
    description: "Google Cloud region where Cloud Run service is located"
    required: true
    default: "us-central1"
  image:
    description: "Full url of container image to be deployed"
    required: true
  revision_tag:
    description: "Optional revision tag to create url"
  revision_suffix:
    description: "Optional revision suffix to use for a unique name"
outputs:
  deployment_id:
    description: "ID of GitHub Deployment created"
  url:
    description: "URL of the Cloud Run service or (revision, if revision_tag is provided)"
runs:
  using: "node12"
  main: "dist/index.js"
